#!/bin/bash
#==============================================================================
# Ralph Loop - Configuration Library
#==============================================================================
# This is a library file meant to be sourced by other scripts.
# It provides functions for generating and managing Ralph Loop configuration.
#
# Usage:
#   source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"
#==============================================================================

# Guard against double-sourcing
if [ -n "$RALPH_CONFIG_LIB_LOADED" ]; then
    return 0
fi
readonly RALPH_CONFIG_LIB_LOADED=true

# Source common library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Ralph version
readonly RALPH_VERSION="2.0.0"

#==============================================================================
# CREATE CONFIG FILE
#==============================================================================
# Generates .ralph/config.sh with project settings.
# Build and test commands are now in separate scripts (build.sh, test.sh).
#
# Parameters:
#   $1 - ralph_dir: Path to .ralph directory
#   $2 - project_name: Name of the project
#   $3 - project_type: Type of project (ios, python, web-react, node, etc.)
#   $4 - agent_type: Type of agent (cursor, auggie, custom)
#   $5 - commit_scope: Git commit scope
#   $6 - max_iterations: Maximum iterations for the loop
#   $7 - build_gate_enabled: Whether build gate is enabled
#==============================================================================
create_config_file() {
    local ralph_dir="$1"
    local project_name="$2"
    local project_type="$3"
    local agent_type="$4"
    local commit_scope="$5"
    local max_iterations="$6"
    local build_gate_enabled="$7"

    local config_file="$ralph_dir/config.sh"

    # Write config file
    cat > "$config_file" << EOF
#!/bin/bash
#
# Ralph Loop - Project Configuration
# Generated by Ralph Loop
#

#==============================================================================
# PROJECT SETTINGS
#==============================================================================

PROJECT_NAME="$project_name"

#==============================================================================
# AGENT SETTINGS
#==============================================================================

AGENT_TYPE="$agent_type"

#==============================================================================
# LOOP SETTINGS
#==============================================================================

MAX_ITERATIONS=$max_iterations
PAUSE_SECONDS=5
MAX_CONSECUTIVE_FAILURES=3

#==============================================================================
# TEST RUN SETTINGS
#==============================================================================

TEST_RUN_ENABLED=true
TEST_RUN_TASKS=2

#==============================================================================
# GIT SETTINGS
#==============================================================================

REQUIRE_BRANCH=true
ALLOWED_BRANCHES=""
AUTO_COMMIT=true
COMMIT_PREFIX="feat"
COMMIT_SCOPE="$commit_scope"

#==============================================================================
# BUILD SETTINGS
#==============================================================================

BUILD_GATE_ENABLED=$build_gate_enabled
BUILD_FIX_ATTEMPTS=1

#==============================================================================
# BUILD/TEST SCRIPTS
#==============================================================================
# Build and test commands are defined in separate scripts:
#   .ralph/build.sh - Build verification script
#   .ralph/test.sh  - Test runner script
#
# Edit these scripts to configure your project's build and test commands.
EOF
}

#==============================================================================
# CREATE BUILD SCRIPT
#==============================================================================
# Copies the placeholder build.sh template to .ralph/build.sh.
# The AI setup assistant will configure it for the specific project.
#
# Parameters:
#   $1 - ralph_dir: Path to .ralph directory
#==============================================================================
create_build_script() {
    local ralph_dir="$1"
    local build_file="$ralph_dir/build.sh"

    cp "$SCRIPT_DIR/../templates/build.sh" "$build_file"
    chmod +x "$build_file"
}

#==============================================================================
# CREATE TEST SCRIPT
#==============================================================================
# Copies the placeholder test.sh template to .ralph/test.sh.
# The AI setup assistant will configure it for the specific project.
#
# Parameters:
#   $1 - ralph_dir: Path to .ralph directory
#==============================================================================
create_test_script() {
    local ralph_dir="$1"
    local test_file="$ralph_dir/test.sh"

    cp "$SCRIPT_DIR/../templates/test.sh" "$test_file"
    chmod +x "$test_file"
}

#==============================================================================
# CREATE PROMPT FILES
#==============================================================================
# Copies placeholder prompt templates to .ralph/.
# The AI setup assistant will configure them for the specific project.
#
# Parameters:
#   $1 - ralph_dir: Path to .ralph directory
#==============================================================================
create_prompt_files() {
    local ralph_dir="$1"

    cp "$SCRIPT_DIR/../templates/platform_prompt.txt" "$ralph_dir/platform_prompt.txt"
    cp "$SCRIPT_DIR/../templates/project_prompt.txt" "$ralph_dir/project_prompt.txt"
}

