#!/bin/bash
#==============================================================================
# Ralph Loop - Configuration Library
#==============================================================================
# This is a library file meant to be sourced by other scripts.
# It provides functions for generating and managing Ralph Loop configuration.
#
# Usage:
#   source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"
#==============================================================================

# Guard against double-sourcing
if [ -n "$RALPH_CONFIG_LIB_LOADED" ]; then
    return 0
fi
readonly RALPH_CONFIG_LIB_LOADED=true

# Source common library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Ralph version
readonly RALPH_VERSION="2.0.0"

#==============================================================================
# CREATE CONFIG FILE
#==============================================================================
# Generates .ralph/config.sh with project settings and platform-specific
# build functions.
#
# Parameters:
#   $1 - ralph_dir: Path to .ralph directory
#   $2 - project_name: Name of the project
#   $3 - project_type: Type of project (ios, python, web-react, node, etc.)
#   $4 - agent_type: Type of agent (cursor, auggie, custom)
#   $5 - xcode_scheme: Xcode scheme (for iOS projects)
#   $6 - xcode_project_dir: Xcode project directory (for iOS projects)
#   $7 - build_command: Build command (for non-iOS projects)
#   $8 - test_command: Test command (for non-iOS projects)
#   $9 - commit_scope: Git commit scope
#   $10 - max_iterations: Maximum iterations for the loop
#   $11 - build_gate_enabled: Whether build gate is enabled
#==============================================================================
create_config_file() {
    local ralph_dir="$1"
    local project_name="$2"
    local project_type="$3"
    local agent_type="$4"
    local xcode_scheme="$5"
    local xcode_project_dir="$6"
    local build_command="$7"
    local test_command="$8"
    local commit_scope="$9"
    local max_iterations="${10}"
    local build_gate_enabled="${11}"

    local config_file="$ralph_dir/config.sh"

    # Map project type to platform type
    local platform_type="generic"
    case "$project_type" in
        ios) platform_type="ios" ;;
        python) platform_type="python" ;;
        web-react|node) platform_type="generic" ;;
        *) platform_type="generic" ;;
    esac

    # Write header
    cat > "$config_file" << 'HEADER'
#!/bin/bash
#
# Ralph Loop - Project Configuration
# Generated by Ralph Loop
#
HEADER

    # Write main configuration sections
    cat >> "$config_file" << EOF
#==============================================================================
# PROJECT SETTINGS
#==============================================================================

PROJECT_NAME="$project_name"
PLATFORM_TYPE="$platform_type"

#==============================================================================
# AGENT SETTINGS
#==============================================================================

AGENT_TYPE="$agent_type"

#==============================================================================
# LOOP SETTINGS
#==============================================================================

MAX_ITERATIONS=$max_iterations
PAUSE_SECONDS=5
MAX_CONSECUTIVE_FAILURES=3

#==============================================================================
# TEST RUN SETTINGS
#==============================================================================

TEST_RUN_ENABLED=true
TEST_RUN_TASKS=2

#==============================================================================
# GIT SETTINGS
#==============================================================================

REQUIRE_BRANCH=true
ALLOWED_BRANCHES=""
AUTO_COMMIT=true
COMMIT_PREFIX="feat"
COMMIT_SCOPE="$commit_scope"

#==============================================================================
# BUILD SETTINGS
#==============================================================================

BUILD_GATE_ENABLED=$build_gate_enabled
BUILD_FIX_ATTEMPTS=1

EOF

    # Add platform-specific settings
    if [ "$project_type" = "ios" ]; then
        cat >> "$config_file" << EOF
#==============================================================================
# iOS BUILD CONFIGURATION
#==============================================================================

XCODE_SCHEME="$xcode_scheme"
XCODE_PROJECT_DIR="$xcode_project_dir"
SIMULATOR_DESTINATION="platform=iOS Simulator,name=iPhone 15"

project_build() {
    cd "\$XCODE_PROJECT_DIR"
    xcodebuild \\
        -scheme "\$XCODE_SCHEME" \\
        -destination "\$SIMULATOR_DESTINATION" \\
        build \\
        2>&1
}

project_test() {
    cd "\$XCODE_PROJECT_DIR"
    xcodebuild \\
        -scheme "\$XCODE_SCHEME" \\
        -destination "\$SIMULATOR_DESTINATION" \\
        test \\
        2>&1
}
EOF
    elif [ -n "$build_command" ]; then
        cat >> "$config_file" << EOF
#==============================================================================
# BUILD COMMANDS
#==============================================================================

project_build() {
    $build_command
}

EOF
        if [ -n "$test_command" ]; then
            cat >> "$config_file" << EOF
project_test() {
    $test_command
}
EOF
        fi
    fi
}

